### ISSUE TITLE
Webcrypto import issue

### ISSUE THREAD

**Issue by alxflw** [muttoni/fcl-sveltekit-quickstart#1]
When starting the project, an import issue is shown:

```
g@As-MacBook-Pro fcl-sveltekit-quickstart % npm run dev -- --open

> fcl-sveltekit@1.0.0 dev /Users/ag/Development/swelte/fcl-sveltekit-quickstart
> svelte-kit dev "--open"

(node:57710) UnhandledPromiseRejectionWarning: file:///Users/ag/Development/swelte/fcl-sveltekit-quickstart/node_modules/@sveltejs/kit/dist/node/polyfills.js:11
import { webcrypto } from 'crypto';
         ^^^^^^^^^
SyntaxError: The requested module 'crypto' does not provide an export named 'webcrypto'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async start (file:///Users/ag/Development/swelte/fcl-sveltekit-quickstart/node_modules/@sveltejs/kit/dist/cli.js:833:24)
    at async file:///Users/ag/Development/swelte/fcl-sveltekit-quickstart/node_modules/@sveltejs/kit/dist/cli.js:911:12
(Use `node --trace-warnings ...` to show where the warning was created)
(node:57710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:57710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by muttoni** [comment]
Hi, unfortunately, not able to replicate (but did update a couple things) - can you try again, and make sure you npm install first?

**Comment by alxflw** [comment]
I did install deps prior but I tried once again (same error) and included by versions - maybe that is helpful:

- NPM: 6.14.15
- Node: v14.18.3

Did more digging and found this: https://nodejs.org/api/crypto.html#cryptowebcrypto. Version added is `v15.0.0`, so the minimum version is 15 - that must be the issue. minor readme update to clarify should resolve this.

**Comment by muttoni** [comment]
yup, new version of sveltekit requires node 16 :) Will clarify! thank you
